import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[window]
dynamic_title = false
dynamic_padding = true

[window.padding]
x = 3
y = 3

[font]
size = 13.5

[font.normal]
family = "Maple Mono"
style = "Regualr"
