import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
dynamic_title = false

[font]
normal = { family = "Maple Mono", style = "Regular" }
size = 13.5
