[theme]
theme = "native"
[theme.overrides]
idle_fg = "#cdd6f4"
info_fg = "#89b4fa"
good_fg = "#a6e3a1"
warning_fg = "#f9e2af"
critical_fg = "#f38ba8"

[icons]
icons = "material-nf"

[[block]]
block = "backlight"

[[block]]
block = "temperature"
format = " $icon $max "
interval = 10
chip = "k10temp-*"
info = 45
warning = 50

[[block]]
block = "temperature"
format = " +$icon $max "
interval = 10
chip = "amdgpu-pci-*"
info = 45
warning = 50

[[block]]
block = "net"
format = " $icon $ip "
interval = 10

[[block]]
block = "battery"
format = " $icon $percentage $power.eng(w:3) $time "
full_format = " $icon "
charging_format = " $icon $percentage $power.eng(w:3) $time "
not_charging_format = " $icon $percentage "
empty_format = " $icon $percentage "
interval = 10

[[block]]
block = "amd_gpu"
interval = 10
format = " $icon $utilization.eng(w:2) "

[[block]]
block = "cpu"
interval = 10
format = " $icon $utilization.eng(w:2) "

[[block]]
block = "load"
interval = 10

[[block]]
block = "disk_space"
interval = 30
info_type = "available"
alert_unit = "GiB"
format = " $icon $available.eng(w:1,prefix:Mi) "

[[block]]
block = "amd_gpu"
interval = 10
format = " $icon $vram_used.eng(w:1,prefix:Mi)~$vram_used_percents.eng(w:1) "

[[block]]
block = "memory"
interval = 10
format = " $icon $mem_used.eng(w:3,prefix:Mi)~$mem_used_percents.eng(w:1) "
format_alt = """ $icon_swap \
	$swap_used.eng(w:3,prefix:Mi)~$swap_used_percents.eng(w:1) """

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 10
format = " $timestamp.datetime(f:'%b/%d %H:%M:%S') "
