#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	echo 'This script requires root privileges!'
	exec sudo "$0" "$@"
fi

if [ "$1" = '1' ]; then
	echo 'Turning off Bluetooth...'
	rfkill block bluetooth
fi

echo 'Reverting configuration...'
echo 'balance_performance' | tee \
	/sys/devices/system/cpu/cpufreq/policy*/energy_performance_preference \
	>/dev/null
echo '800000' | tee \
	/sys/devices/system/cpu/cpufreq/policy*/scaling_min_freq >/dev/null
echo '3000000' | tee \
	/sys/devices/system/cpu/cpufreq/policy*/scaling_max_freq >/dev/null
echo '1' | tee /sys/devices/system/cpu/cpufreq/boost >/dev/null

echo 'auto' | tee \
	/sys/class/drm/card*/device/power_dpm_force_performance_level >/dev/null
echo 'balanced' | tee /sys/class/drm/card*/device/power_dpm_state >/dev/null
echo '3' | tee /sys/class/drm/card*/device/pp_power_profile_mode >/dev/null

echo '1' | tee /sys/class/thermal/thermal_zone0/cdev*/cur_state >/dev/null

sleep 5

echo 'Applying changes...'
echo 'power' | tee \
	/sys/devices/system/cpu/cpufreq/policy*/energy_performance_preference \
	>/dev/null
echo '400000' | tee \
	/sys/devices/system/cpu/cpufreq/policy*/scaling_min_freq >/dev/null
#echo '1000000' | tee \
#	/sys/devices/system/cpu/cpufreq/policy*/scaling_max_freq >/dev/null
echo '0' | tee /sys/devices/system/cpu/cpufreq/boost >/dev/null

echo 'low' | tee \
	/sys/class/drm/card*/device/power_dpm_force_performance_level >/dev/null
echo 'battery' | tee /sys/class/drm/card*/device/power_dpm_state >/dev/null
echo '1' | tee /sys/class/drm/card*/device/pp_power_profile_mode >/dev/null

echo '3' | tee /sys/class/thermal/thermal_zone0/cdev*/cur_state >/dev/null

echo '80' | tee \
	/sys/class/power_supply/BAT0/charge_control_end_threshold >/dev/null

echo 'Applied successfully C:'
