#!/bin/sh

[ "$(id -u)" -ne 0 ] && exec sudo "$0" "$@"

pkill parre && {
	echo 'Killed parre, waiting...'
	while pgrep -x parre >/dev/null; do
		sleep 0.1
	done
}

for cmd in '\_SB.PCI0.SBRG.EC0.WRAM 0xCD 0x30 0x85' \
	'\_SB.PCI0.SBRG.EC0.WRAM 0xCD 0x37 0x8b'; do
	echo "$cmd" | tee /proc/acpi/call >/dev/null
done

echo 'BIOS/ACPI Mode set successfully.'
