import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[window]
dynamic_padding = true

[window.padding]
x = 3
y = 3

[font]
size = 15
builtin_box_drawing = false

[font.normal]
family = "JetBrains Mono"
