[theme]
theme = 'native'
[theme.overrides]
idle_fg = '#cdd6f4'
info_fg = '#a6e3a1'
good_fg = '#f9e2af'
warning_fg = '#fab387'
critical_fg = '#f38ba8'
[icons]
icons = 'material-nf'
[icons.overrides]
backlight = [
	'󰪞',
	'󰪟',
	'󰪠',
	'󰪡',
	'󰪢',
	'󰪣',
	'󰪤',
	'󰪥'
]
cpu = ''
memory_mem = ''

[[block]]
block = 'scratchpad'
[block.theme_overrides]
idle_fg = '#f8e2af'

[[block]]
block = 'keyboard_layout'
driver = 'sway'
[block.mappings]
'English (US)' = 'EN'
'Persian (N/A)' = 'FA'
[block.theme_overrides]
idle_fg = '#cba6f7'

[[block]]
block = 'backlight'

[[block]]
block = 'temperature'
format = ' $icon $max '
interval = 5
chip = 'k10temp-*'
info = 45
warning = 50

[[block]]
block = 'net'
device = 'wlp2s0'
format = """ $speed_down.eng(w:1) ^icon_net_down \
	$speed_up.eng(w:1) ^icon_net_up """
format_alt = ' ^icon_net_wireless $ssid '
interval = 2

[[block]]
block = 'battery'
format = ' $icon $percentage $power.eng(w:3) $time '
full_format = ' $icon '
charging_format = ' $icon $percentage $power.eng(w:3) $time '
not_charging_format = ' $icon $percentage '
empty_format = ' $icon $percentage '
interval = 10

[[block]]
block = 'amd_gpu'
interval = 5
format = ' $icon $utilization.eng(w:2) '

[[block]]
block = 'cpu'
interval = 5
format = ' $icon $utilization.eng(w:2) '

[[block]]
block = 'load'
interval = 5

[[block]]
block = 'disk_space'
interval = 30
info_type = 'available'
alert_unit = 'GiB'
format = ' $icon $available.eng(w:1,prefix:Mi) '

[[block]]
block = 'memory'
interval = 10
format = ' $icon $mem_used.eng(w:3,prefix:Mi)~$mem_used_percents.eng(w:1) '
format_alt = """ $icon_swap \
	$swap_used.eng(w:3,prefix:Mi)~$swap_used_percents.eng(w:1) """

[[block]]
block = 'sound'
driver = 'auto'

[[block]]
block = 'time'
interval = 10
format = " $timestamp.datetime(f:'%b-%d %H:%M:%S') "
