#!/bin/sh

set -e
set -u

bounce() {
	printf "$1 \e[31m):\e[0m\n"
	exit 1
}

dust="$(CDPATH= cd -- "$(dirname -- "$0")" && cd .. && pwd -P)"

printf "Low or high? [L/h] "
read stat
if [ "$stat" = "H" ] || [ "$stat" = "h" ]; then
	setup="setup-hi"
	picom="picom-hi.conf"
else
	setup="setup-lo"
	picom="picom-lo.conf"
fi

if [ -f "$dust/scripts/$setup" ]; then
	rm -f "$dust/scripts/setup"
	ln -s "$dust/scripts/$setup" "$dust/scripts/setup"
	"$dust/scripts/setup"
else
	bounce "Failed to create symlink for $setup"
fi

if [ -f "$dust/.config/picom/$picom" ]; then
	rm -f "$dust/.config/picom/picom.conf"
	ln -s "$dust/.config/picom/$picom" "$dust/.config/picom/picom.conf"
	pkill -SIGUSR1 picom
else
	bounce "Failed to create symlink for $picom"
fi

echo "Dsetted <:"
