#!/usr/bin/env perl
use 5.040;
use strict;
use warnings;

my $key = 'x';

sub bounce {
	say "[ERROR] $_[0]";
	exit 1;
}

@ARGV or bounce 'No files provided. Please specify one or more files to process.';

for my $file (@ARGV) {
	open my $in, '<:raw', $file or bounce "Can't open $file for reading >=";
	binmode $in;
	my $data = do { local $/; <$in> };
	close $in or bounce "Can't close $file after reading >=";

	$data ^.= ($key x length $data);

	open my $out, '>:raw', $file or bounce "Can't open $file for writin >=";
	binmode $out;
	print $out $data or bounce "Can't write to $file >=";
	close $out or bounce "Can't close $file after writing >=";

	say "Processed ", length($data), " bytes from $file.";
}
