#!/bin/bash

set -e

bounce() {
	echo "$1" >&2
	exit 1
}

for cmd in maim xclip; do
	command -v "$cmd" &>/dev/null || bounce "$cmd not found. Please install it first!"
done

scdir="$HOME/Pictures/Screenshots"
fileName="$scdir/screenshot_$(date +'%Y-%b-%d_%H-%M-%S').jpg"
mkdir -p "$scdir" || bounce "Failed to create directory: $scdir >:"

if [[ "$1" == "--select" || "$1" == "-s" ]]; then
	maim -m 8 -s -D "$fileName" || bounce 'Failed to take screenshot >:'
else
	maim -m 8 "$fileName" || bounce 'Failed to take screenshot >:'
fi

[[ -f "$fileName" ]] || bounce 'Screenshot file not created >:'
xclip -selection clipboard -t image/jpeg -i "$fileName" || bounce 'Failed to copy screenshot to clipboard >:'
