#!/bin/sh

set -e
set -u

bounce() {
	printf "${1:-Broken for a reason} \e[31m):\e[0m\n"
	exit 1
}

if [ "$(id -u)" -ne 0 ]; then
	echo "This script requires root privileges. Elevating..."
	exec sudo "$0" "$@"
fi

if [ "${1:-0}" -eq 1 ]; then
	echo "Turning Bluetooth off..."
	rfkill block bluetooth || bounce "Failed to disable Bluetooth"
fi

echo "Resetting values..."
echo "balance_performance" |
	tee /sys/devices/system/cpu/cpufreq/policy*/energy_performance_preference
echo "800000" | tee /sys/devices/system/cpu/cpufreq/policy*/scaling_min_freq
echo "2000000" | tee /sys/devices/system/cpu/cpufreq/policy*/scaling_max_freq
echo "0" | tee /sys/devices/system/cpu/cpufreq/boost

echo "auto" |
	tee /sys/class/drm/card*/device/power_dpm_force_performance_level
echo "balanced" | tee /sys/class/drm/card*/device/power_dpm_state
echo "3" | tee /sys/class/drm/card*/device/pp_power_profile_mode

echo "1" | tee /sys/class/thermal/thermal_zone0/cdev*/cur_state

sleep 1

echo "Applying new settings..."
echo "balance_power" |
	tee /sys/devices/system/cpu/cpufreq/policy*/energy_performance_preference
echo "400000" | tee /sys/devices/system/cpu/cpufreq/policy*/scaling_min_freq
echo "3000000" | tee /sys/devices/system/cpu/cpufreq/policy*/scaling_max_freq
echo "1" | tee /sys/devices/system/cpu/cpufreq/boost

echo "low" |
	tee /sys/class/drm/card*/device/power_dpm_force_performance_level
echo "battery" | tee /sys/class/drm/card*/device/power_dpm_state
echo "1" | tee /sys/class/drm/card*/device/pp_power_profile_mode

echo "3" | tee /sys/class/thermal/thermal_zone0/cdev*/cur_state

echo "80" | tee /sys/class/power_supply/BAT0/charge_control_end_threshold

echo "Hardware settings applied successfully."
