#!/bin/sh

set -u

bounce() {
	printf "$1 \e[31m):\e[0m\n"
	exit 1
}

if [ "$(id -u)" -ne 0 ]; then
	echo "This script requires root privileges. Elevating..."
	exec sudo "$0" "$@"
fi

if [ "$1" -eq 1 ]; then
	echo "Turning Bluetooth off..."
	rfkill block bluetooth || bounce "Failed to disable Bluetooth"
fi

echo "Resetting values..."
printf "balance_performance" |
	tee /sys/devices/system/cpu/cpufreq/policy*/energy_performance_preference
printf "800000" | tee /sys/devices/system/cpu/cpufreq/policy*/scaling_min_freq
printf "2000000" | tee /sys/devices/system/cpu/cpufreq/policy*/scaling_max_freq
printf "0" | tee /sys/devices/system/cpu/cpufreq/boost

printf "auto" |
	tee /sys/class/drm/card*/device/power_dpm_force_performance_level
printf "balance" | tee /sys/class/drm/card*/device/power_dpm_state
printf "3" | tee /sys/class/drm/card*/device/pp_power_profile_mode

printf "1" | tee /sys/class/thermal/thermal_zone0/cdev*/cur_state

sleep 1.101

echo "Applying new settings..."
printf "balance_power" |
	tee /sys/devices/system/cpu/cpufreq/policy*/energy_performance_preference
printf "400000" | tee /sys/devices/system/cpu/cpufreq/policy*/scaling_min_freq
printf "2600000" | tee /sys/devices/system/cpu/cpufreq/policy*/scaling_max_freq
printf "1" | tee /sys/devices/system/cpu/cpufreq/boost

printf "low" |
	tee /sys/class/drm/card*/device/power_dpm_force_performance_level
printf "battery" | tee /sys/class/drm/card*/device/power_dpm_state
printf "1" | tee /sys/class/drm/card*/device/pp_power_profile_mode

printf "3" | tee /sys/class/thermal/thermal_zone0/cdev*/cur_state

printf "80" | tee /sys/class/power_supply/BAT0/charge_control_end_threshold

echo "Hardware settings applied successfully <:"
