#!/bin/bash

if [[ $(id -u) -ne 0 ]]; then
	echo 'This script requires root privileges. Elevating...'
	exec sudo "$0" "$@"
fi

if [[ $1 -eq 1 ]]; then
	echo 'Turning off Bluetooth...'
	rfkill block bluetooth || { echo 'Failed to disable Bluetooth >:'; exit 1; }
fi

echo 'Resetting values...'
tee /sys/devices/system/cpu/cpufreq/policy*/energy_performance_preference <<< 'balance_performance'
tee /sys/devices/system/cpu/cpufreq/policy*/scaling_min_freq <<< '800000'
tee /sys/devices/system/cpu/cpufreq/policy*/scaling_max_freq <<< '2000000'
tee /sys/devices/system/cpu/cpufreq/boost <<< '1'

tee /sys/class/drm/card*/device/power_dpm_force_performance_level <<< 'auto'
tee /sys/class/drm/card*/device/power_dpm_state <<< 'balanced'
tee /sys/class/drm/card*/device/pp_power_profile_mode <<< '3'

tee /sys/class/thermal/thermal_zone0/cdev*/cur_state <<< '1'

sleep 1.101

echo 'Applying new settings...'
tee /sys/devices/system/cpu/cpufreq/policy*/energy_performance_preference <<< 'power'
tee /sys/devices/system/cpu/cpufreq/policy*/scaling_min_freq <<< '400000'
tee /sys/devices/system/cpu/cpufreq/policy*/scaling_max_freq <<< '1800000'
tee /sys/devices/system/cpu/cpufreq/boost <<< '0'

tee /sys/class/drm/card*/device/power_dpm_force_performance_level <<< 'low'
tee /sys/class/drm/card*/device/power_dpm_state <<< 'battery'
tee /sys/class/drm/card*/device/pp_power_profile_mode <<< '1'

tee /sys/class/thermal/thermal_zone0/cdev*/cur_state <<< '3'

tee /sys/class/power_supply/BAT0/charge_control_end_threshold <<< '80'

echo 'Hardware settings applied successfully <:'
