#!/bin/sh

set -e
set -u

bounce() {
	printf "${1:-Broken for a reason} \e[31m):\e[0m\n"
	exit 1
}

deviceName="ASUE1A01:00 04F3:31D4 Touchpad"
deviceId="$(xinput list --id-only "$deviceName" 2>/dev/null)"

if [ -z "$deviceId" ]; then
	bounce "Device '$deviceName' not found"
fi

state="$(xinput list-props "$deviceId" | \
	grep 'Device Enabled' | grep -o '[01]$')"

if [ "$state" -eq 1 ]; then
	xinput --disable "$deviceId"
else
	xinput --enable "$deviceId"
fi
