#!/bin/bash

deviceName="ASUE1A01:00 04F3:31D4 Touchpad"
deviceId=$(xinput list --id-only "$deviceName" 2>/dev/null)

if [[ -z "$deviceId" ]]; then
	echo "[ERROR] Device '$deviceName' not found >="
	exit 1
fi

state=$(xinput list-props "$deviceId" | grep 'Device Enabled' | grep -o '[01]$')

if [[ $state -eq 1 ]]; then
	xinput --disable "$deviceId"
else
	xinput --enable "$deviceId"
fi
