[general]
import = [ "~/.config/alacritty/abstract-dark.toml" ]

[window]
dynamic_padding = true

[window.padding]
x = 1
y = 1

[font]
size = 18

[font.normal]
family = "Agave"

[font.offset]
x = 0
y = 3

[font.glyph_offset]
x = 0
y = 1
