[general]
import = [ '~/.config/alacritty/abstract-dark.toml' ]

[window]
dynamic_padding = true

[window.padding]
x = 0
y = 0

[font]
size = 21

[font.normal]
family = 'Agave'

[font.offset]
x = 0
y = 2
