[general]
import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[window]
dynamic_padding = true

[window.padding]
x = 2
y = 2

[font]
size = 16

[font.normal]
family = "JetBrains Mono"
style = "Medium"

[font.bold]
style = "ExtraBold"
