set -s escape-time 0
set -g terminal-features 'alacritty:RGB'
set -g status-right ''
set -g repeat-time 999

set -g prefix C-Space
bind C-Space send-prefix

bind | split-window -h
bind - split-window -v

bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

bind -r C-h resize-pane -L 3
bind -r C-l resize-pane -R 3
bind -r C-k resize-pane -U 3
bind -r C-j resize-pane -D 3

bind -r L next-window
bind -r H previous-window

bind -r '<' swap-window -t -1 -d
bind -r '>' swap-window -t +1 -d

bind r {
    source-file ~/.config/tmux/tmux.conf;
    display 'Reloaded!';
}
bind x confirm-before -p 'kill-pane #P? (Y/N)' kill-pane
